# Generated by Django 4.2.7 on 2025-11-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0002_assetcategory_budget_deliverynote_goodsreceivednote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobilemoneyaccount",
            name="currency_code",
            field=models.CharField(
                blank=True,
                help_text="Currency code (e.g., USD, ZWL)",
                max_length=10,
                null=True,
            ),
        ),
    ]
