# Generated by Django 4.2.7 on 2025-11-06 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0003_add_currency_code_to_mobile_money_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashTill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=100)),
                (
                    "currency_code",
                    models.CharField(
                        blank=True,
                        help_text="Currency code (e.g., USD, ZWL)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_tills",
                        to="erp.store",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["store"], name="erp_cashtil_store_i_7fce22_idx"
                    ),
                    models.Index(
                        fields=["account_name"], name="erp_cashtil_account_0dede9_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="erp_cashtil_is_acti_b313f1_idx"
                    ),
                ],
            },
        ),
    ]
