# Generated by Django 4.2.7 on 2025-11-07 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0004_cashtill"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="Store this product belongs to (optional for multi-store scenarios)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="erp.store",
            ),
        ),
        migrations.AddField(
            model_name="salesession",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="Store where this POS session is active",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_sessions",
                to="erp.store",
            ),
        ),
    ]
