# Generated by Django 4.2.7 on 2025-11-08 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0005_add_store_to_product_and_sale_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="address_line1",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendors",
                to="erp.business",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_vendors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="province",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_type",
            field=models.CharField(
                choices=[
                    ("SUPPLIER", "Supplier"),
                    ("CONTRACTOR", "Contractor"),
                    ("SERVICE_PROVIDER", "Service Provider"),
                    ("MANUFACTURER", "Manufacturer"),
                ],
                default="SUPPLIER",
                max_length=20,
            ),
        ),
    ]
