# Generated by Django 4.2.7 on 2025-11-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0006_update_vendor_model_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vendor",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="is_inventory_item",
            field=models.BooleanField(
                default=True,
                help_text="If True, item will be added to inventory when received",
            ),
        ),
    ]
