# Generated by Django 4.2.7 on 2025-11-08 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0007_add_is_inventory_item_to_purchase_order_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Link to existing product, or leave blank for custom items",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.product",
            ),
        ),
    ]
