# Generated by Django 4.2.7 on 2025-11-08 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0008_make_purchase_order_item_product_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceivednote",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="goodsreceivednote",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Payment"),
                    ("PARTIAL", "Partially Paid"),
                    ("PAID", "Fully Paid"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceivednote",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name="PurchaseOrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("BANK", "Bank Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erp.bankaccount",
                    ),
                ),
                (
                    "cash_till",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erp.cashtill",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="erp.goodsreceivednote",
                    ),
                ),
                (
                    "mobile_money_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erp.mobilemoneyaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
                "indexes": [
                    models.Index(
                        fields=["grn", "payment_method"],
                        name="erp_purchas_grn_id_9a2ffa_idx",
                    )
                ],
            },
        ),
    ]
