# Generated by Django 4.2.7 on 2025-11-08 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0009_add_payment_fields_to_grn"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "service_code",
                    models.CharField(
                        help_text="Unique service code/identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(blank=True, default="General", max_length=50),
                ),
                (
                    "service_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price for this service",
                        max_digits=10,
                    ),
                ),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated duration in hours (optional)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="erp.business",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        help_text="Store this service belongs to (optional for multi-store scenarios)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="erp.store",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Services",
                "indexes": [
                    models.Index(
                        fields=["business"], name="erp_service_busines_15c7f2_idx"
                    ),
                    models.Index(
                        fields=["service_code"], name="erp_service_service_ab05b2_idx"
                    ),
                    models.Index(
                        fields=["category"], name="erp_service_categor_770e4b_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="erp_service_is_acti_9119a7_idx"
                    ),
                ],
            },
        ),
    ]
