# Generated by Django 4.2.7 on 2025-11-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0010_add_service_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="positem",
            name="item_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the item (product or service)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="positem",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="Service for this item (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.service",
            ),
        ),
        migrations.AlterField(
            model_name="positem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Product for this item (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="erp.product",
            ),
        ),
        migrations.AddIndex(
            model_name="positem",
            index=models.Index(
                fields=["service"], name="erp_positem_service_5d7966_idx"
            ),
        ),
    ]
