# Generated by Django 4.2.7 on 2025-11-10 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0011_add_service_to_pos_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill_number",
                    models.CharField(
                        db_index=True,
                        help_text="Vendor bill/invoice number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, help_text="Internal reference", max_length=100
                    ),
                ),
                ("bill_date", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("TO_APPROVE", "To Approve"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PARTIAL", "Partially Paid"),
                            ("PAID", "Paid"),
                        ],
                        default="UNPAID",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes not visible to vendor"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_vendor_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_bills",
                        to="erp.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_vendor_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="erp.currency"
                    ),
                ),
                (
                    "grn",
                    models.ForeignKey(
                        blank=True,
                        help_text="GRN this bill is linked to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_bills",
                        to="erp.goodsreceivednote",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_bills",
                        to="erp.purchaseorder",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_vendor_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_vendor_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_bills",
                        to="erp.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-bill_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorBillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("unit_of_measure", models.CharField(default="Units", max_length=50)),
                ("notes", models.TextField(blank=True)),
                (
                    "grn_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to GRN item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erp.goodsreceivednoteitem",
                    ),
                ),
                (
                    "po_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to purchase order item",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erp.purchaseorderitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erp.product",
                    ),
                ),
                (
                    "vendor_bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="erp.vendorbill",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["vendor_bill"], name="erp_vendorb_vendor__195ed1_idx"
                    ),
                    models.Index(
                        fields=["po_item"], name="erp_vendorb_po_item_04cc50_idx"
                    ),
                    models.Index(
                        fields=["product"], name="erp_vendorb_product_ae8106_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(
                fields=["business", "status"], name="erp_vendorb_busines_4b8e60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(
                fields=["vendor"], name="erp_vendorb_vendor__a4ba92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(
                fields=["purchase_order"], name="erp_vendorb_purchas_34b6a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(fields=["grn"], name="erp_vendorb_grn_id_cf0e34_idx"),
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(
                fields=["bill_number"], name="erp_vendorb_bill_nu_a79567_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorbill",
            index=models.Index(
                fields=["payment_status"], name="erp_vendorb_payment_221259_idx"
            ),
        ),
    ]
